import Navbar from "@/components/Navbar";
import "../globals.css";
import { Inter } from "next/font/google";
import AdminNavbar from "@/components/AdminNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="admin__dashboard flex">
      <Navbar />

      <AdminNavbar />
      <div className="page__contents mt-24 ml-[260px] p-10 w-full">
        {children}
      </div>
    </div>
  );
}
